/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Utils.DatabaseUtils;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import models.Product;

/**
 *
 * @author User
 */
public class CreateForm extends javax.swing.JPanel {

    /**
     * Creates new form CreateForm
     */
    
    JSplitPane splitPane;
    JPanel bottomPanel;
    public CreateForm(JPanel bottomPanel, JSplitPane splitPane) {
        this.bottomPanel = bottomPanel;
        this.splitPane = splitPane;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        tbnInsert = new javax.swing.JButton();
        btnViewPane = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Price:");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tbnInsert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbnInsert.setText("Insert");
        tbnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnInsertActionPerformed(evt);
            }
        });

        btnViewPane.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnViewPane.setText("View products");
        btnViewPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(tbnInsert)
                        .addGap(38, 38, 38)
                        .addComponent(btnViewPane)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbnInsert)
                    .addComponent(btnViewPane))
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnInsertActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isBlank() || txtPrice.getText().isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please fill all fields ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (DatabaseUtils.insertProduct(new Product(txtName.getText().trim(), 
                    Double.parseDouble(txtPrice.getText().trim())))) {
                JOptionPane.showMessageDialog(
                        this,
                        "Success! Product inserted", "Done", JOptionPane.INFORMATION_MESSAGE);
                txtName.setText("");
                txtPrice.setText("");
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Fatal Error Item Insertion Failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tbnInsertActionPerformed

    private void btnViewPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPaneActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel titleLabel = (javax.swing.JLabel)splitPane.getTopComponent();
        ViewForm display = new ViewForm(bottomPanel, titleLabel);
        bottomPanel.add(display);
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        titleLabel.setText("View Products");
        cl.next(bottomPanel);
        
        
        
        
    }//GEN-LAST:event_btnViewPaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tbnInsert;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}




